# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  example.com:
    site_hosts:
      - blog.newdot.local
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: Newdot
    admin_user: juandiego
    # admin_password: (defined in group_vars/development/vault.yml)
    admin_email: juandiego@blog.newdot.local
    initial_permalink_structure: /%postname%/ # applied only at time of WP install and when `site_install: true`
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://blog.newdot.local
      wp_siteurl: http://blog.newdot.local/wp
      wp_env: development
      db_name: blognewdot_dev
      db_user: blognewdot_dbuser
      # db_password: (defined in group_vars/development/vault.yml)
