---
- include: database.yml
  tags: wordpress-setup-database
- include: self-signed-certificate.yml
  tags: wordpress-setup-self-signed-certificate
- include: nginx.yml
  tags: wordpress-setup-nginx

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: wordpress_sites

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: wordpress_sites

- name: Setup WP system cron
  cron:
    name: "{{ item.key }} WordPress cron"
    minute: "*/15"
    user: "{{ web_user }}"
    job: "curl -k -s {{ item.value.env.wp_siteurl }}/wp-cron.php > /dev/null 2>&1"
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: wordpress_sites
  when: item.value.env.disable_wp_cron | default(false) and not item.value.multisite.enabled | default(false)
