# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  blog.newdot.co:
    site_hosts:
      - blog.newdot.co
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:Newdotco/blog.newdot.co.git # replace with your Git repo URL
    branch: master
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
      # cert: ~/ssl/blog.newdot.co.crt
      # key: ~/ssl/blog.newdot.co.key
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://blog.newdot.co
      wp_siteurl: http://blog.newdot.co/wp
      wp_env: production
      db_name: blognewdot_prod
      db_user: blognewdot_dbuser
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
